services:
  app:
    build: app
    volumes:
      - ./app:/app
    command: npm run dev
    ports:
      - "3000:3000"
    env_file: .env

  front:
    image: node:22-alpine
    volumes:
      - ./front:/app
    working_dir: /app
    ports:
      - 3001:3000
    command: npm run dev -- -o
    env_file: .env
