services:
  app:
    build: app
    volumes:
      - ./app:/app
    command: npm run dev
    ports:
      - "3000:3000"
    environment:
      - WEATHERBIT_APIKEY=${WEATHERBIT_APIKEY}

volumes:
  database:
